### ISSUE TITLE
Some pipelineruns are in finished state but no result stored

### ISSUE THREAD

**Issue by jia-jerry** [SAP/stewardci-core#243]
suspicious code: https://github.com/SAP/stewardci-core/blob/master/pkg/runctl/controller.go#L376

https://github.com/SAP/stewardci-core/blob/master/pkg/runctl/controller.go#L394

State is saved before the result. 
We should change the order.

Or further enhancement: Save the PR only once if changed information should be in one transaction.

**Comment by marcusholl** [comment]
After having a first look over the coding I think changing the order will not change the situation. The point is - in my understanding - to update the PR _only once_ with several changes.

The PR might be fetched by the build-syncer between two updates (state/result) regardless of the order of the lines when they are updated one after each other.

**Comment by rinckm** [comment]
I think line https://github.com/SAP/stewardci-core/blob/master/pkg/runctl/controller.go#L402 is more problematic.
If for a running SPR the tekton task is deleted it will finish without result being set.

**Comment by anbrsap** [comment]
Fixed by #248
